### ISSUE TITLE
Data layout interacts poorly with copy-on-write

### ISSUE THREAD

**Issue by sgrif** [withoutboats/shifgrethor#4]
This was a major problem for Ruby for a long time. Since you're tracking whether an object has been marked inline next to the data being managed, forked process will not be able to share any managed memory, even if neither process actually intends to write to large segments of it. As soon as either process runs the garbage collector, the entire managed heap will need to be copied. Ruby solved this by using a separate bitmap to track marking.

**Comment by withoutboats** [comment]
I think this is out of scope for the current project because it is an implementation detail that doesn't impact the public API (which is what shifgrethor is specifically trying to research). As it stands, the implementation isn't even thread-safe, much less supporting shared access between processes.

**Comment by sgrif** [comment]
:+1:

**Comment by withoutboats** [comment]
Let me know if you see something in the public API that would prevent an implementation from doing this though!
